--CREATE TABLE helousers (
--  id SERIAL PRIMARY KEY,
--  username varchar(20),
--  passw varchar(30),
--  profile_pic text 
--);

--CREATE TABLE heloposts (
--id SERIAL PRIMARY KEY,
--title varchar(45),
--img text,
--content text,
--author_id integer,
--FOREIGN KEY (author_id) REFERENCES helousers(id)
--)